# Generated by Django 4.1.7 on 2023-03-30 13:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('fichier_CV', models.FileField(upload_to='pdf_files/')),
                ('fichier_photo', models.ImageField(blank=True, upload_to='')),
                ('lien_linkedln', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellé', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_debut', models.DateField(default=datetime.date.today, null=True)),
                ('date_fin', models.DateField(default=datetime.date.today, null=True)),
                ('achevé', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.service')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membres', models.ManyToManyField(to='ArtyProd.personnel')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Détail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membres', models.ManyToManyField(to='ArtyProd.personnel')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.projet')),
            ],
        ),
    ]
