# Generated by Django 4.1.7 on 2023-04-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0004_alter_personnel_fonction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='localisation',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='numéro_tel',
        ),
        migrations.AlterField(
            model_name='personnel',
            name='lien_facebook',
            field=models.CharField(default='https://www.facebook.com/', max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='lien_github',
            field=models.CharField(default='https://github.com/', max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='lien_linkedln',
            field=models.CharField(default='https://www.linkedin.com/', max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='lien_twitter',
            field=models.CharField(default='https://twitter.com/', max_length=100),
        ),
    ]
