# Generated by Django 4.1.7 on 2023-04-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0005_remove_contact_email_remove_contact_localisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='nom',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='détail',
            name='detail_Project',
            field=models.FileField(null=True, upload_to='pdf_files/'),
        ),
        migrations.AddField(
            model_name='service',
            name='nom',
            field=models.CharField(default='', max_length=20),
        ),
    ]
