# Generated by Django 4.1.7 on 2023-05-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0006_contact_nom_détail_detail_project_service_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images_Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.projet')),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='images',
            field=models.ManyToManyField(blank=True, to='ArtyProd.images_projet'),
        ),
    ]
