# Generated by Django 4.1.7 on 2023-05-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0008_temoignage'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoignage',
            name='image',
            field=models.ImageField(null=True, upload_to='temoignage-images/'),
        ),
    ]
