# Generated by Django 4.1.7 on 2023-05-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0009_temoignage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='service',
            name='type',
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('graphic_design', 'Graphic Design'), ('audiovisual_production', 'Audiovisual Production'), ('three_d_conception', '3D Conception')], max_length=50, null=True),
        ),
    ]
