# Generated by Django 4.1.7 on 2023-05-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0010_remove_service_nom_remove_service_type_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
