# Generated by Django 4.1.7 on 2023-05-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0012_remove_projet_service_projet_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('lien_linkedln', models.CharField(default='https://www.linkedin.com/', max_length=100)),
                ('lien_twitter', models.CharField(default='https://twitter.com/', max_length=100)),
                ('lien_facebook', models.CharField(default='https://www.facebook.com/', max_length=100)),
                ('intagram', models.CharField(default='https://www.facebook.com/', max_length=100)),
            ],
        ),
    ]
