# Generated by Django 4.1.7 on 2023-05-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0013_contact_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='nom',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='objet',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='username',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
