# Generated by Django 4.1.7 on 2023-05-22 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ArtyProd', '0014_remove_contact_nom_contact_message_contact_objet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
